version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build: ./live-builds/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  mysql8:
    image: mysql:8.0.17
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: mysql8
    ports:
      - "33060:3306"
    volumes:
      - ./db-data:/var/lib/mysql:delegated
    working_dir: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  php-fpm-81:
    container_name: php-fpm-81
    build: live-builds/php-fpm-81
    volumes:
      - ../:/var/www/
    working_dir: /var/www
    links:
      - mysql8

  php-fpm-82:
    container_name: php-fpm-82
    build: live-builds/php-fpm-82
    volumes:
      - ../:/var/www/
    working_dir: /var/www
    links:
      - mysql8

  divelog:
    container_name: divelog-api
    build: ./live-builds/divelog-api
    environment:
      - VIRTUAL_HOST=divelog-api.test
    volumes:
      - ../2022-divelog-api:/var/www/2023-divelog-api
    working_dir: /var/www/2023-divelog-api
    depends_on:
      - php-fpm-82

  butter:
    container_name: butter
    build: ./live-builds/butter
    environment:
      - VIRTUAL_HOST=butter.test
    volumes:
      - ../2022-divelog-api:/var/www/butter
    working_dir: /var/www/butter
    depends_on:
      - php-fpm-82